version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ACE_STREAM_URL=http://192.168.0.99:6878/ace/manifest.m3u8
    volumes:
      - .:/app
      # Exclude node_modules and .next from volume mounting
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3
