version: '3.8'

services:
  app:
    image: scraper-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scraper-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ACE_STREAM_URL=http://localhost:6878/ace/manifest.m3u8
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--spider', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 3

  acestream:
    image: wafy80/acestream
    container_name: acestream
    ports:
      - '6878:6878'
    restart: unless-stopped
